# Generated by Django 4.0 on 2021-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_model',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
