# Generated by Django 4.0 on 2021-12-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
