# Generated by Django 4.0 on 2021-12-21 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_alter_feed_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='likes',
        ),
        migrations.AddField(
            model_name='feed',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='feeds_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
