# Generated by Django 4.0 on 2021-12-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_feed_likes_feed_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='comment'),
            preserve_default=False,
        ),
    ]
